spring.application.name=zorvynBackend
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/finance_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:boom}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET:65fa6ad0e5906d3008205b517ca5e8b90948f1a2506d8d647aacf9523d6f1f19f885a89e5aeafc2a4296fe2357faf2c15fc016410f773e4566235a5d3d55a8cc}
jwt.expiration=${JWT_EXPIRATION:86400000}

app.admin-secret=${APP_ADMIN_SECRET:hoooha}